# Generated by Django 4.0.2 on 2022-10-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='techStack',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='updated_at',
        ),
    ]
