# Generated by Django 4.1.2 on 2022-10-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_category_quizzes_question_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="username",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.student",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="user_name",
            field=models.CharField(max_length=100),
        ),
    ]
